# Python Homework (NumPy, Pandas)

**Note**: You can create a Python file or a Jupyter Notebook file

<br>

<ins>Use markdown formatting for the following questions (e.g., bold lettering, bullet points, different font sizes, etc.)</ins>: 
1. What does Pandas stand for?

    1. Panel Data 
    2. Python Data Analysis

2. What are the 2 collections used in Pandas?

    1. Pandas Series
    2. Pandas DataFrames

3. Name 4 things Pandas can do for us.

    1. Data Cleansing
    2. Data fill
    3. Data normalization
    4. Merges and joins

4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?

    inplace=True

5. What is a CSV?

    CSV =Comma-Separated Values(comma separated files): simple file format used to store  data like spreadsheets

6. When cleaning data what values do we not like in our data?

    NULL values


<br>


7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()

In [13]:
import numpy as np
array1 = [
            [
                    (1, 2),
                    (3, 4),
                    (5, 6)
            ],
            
            [
                    (7, 8),
                    (9, 10),
                    (11, 12)
            ]

]
print(np.ndim(array1), "shape:", np.shape(array1))
# Initializing the arrays
arr = np.arange(12, dtype = np.int_).reshape(2, 3, 2)
print("arr ...\n", arr)


3 shape: (2, 3, 2)
arr ...
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

In [19]:
array2 = np.linspace(0, 20, 6)
print("arr ...\n", array2)

arr ...
 [ 0.  4.  8. 12. 16. 20.]


9. Make a Deep Copy of the above array

In [ ]:
array3 = array2.copy()
print("\nDeep copy of the array:\n", array3)


Deep copy of the array:
 [ 0.  4.  8. 12. 16. 20.]


TypeError: shape() missing 1 required positional argument: 'a'

10. Concatenate these 3 arrays into a new array named 'newArray'... ([[25, 16]]) ([[11, 2], [13, 4]]) ([[7, 81], [5, 6], [11, 12]]) ```python

In [45]:
array1 = np.array([[25, 16]])             
array2 = np.array([[11, 2], [13, 4]])      
array3 = np.array([[7, 81], [5, 6], [11, 12]]) 
print("\narry1 Dim: ", np.ndim(array1), "shape:", np.shape(array1))
print("\narry3 Dim: ", np.ndim(array2), "shape:", np.shape(array2))
print("\narry3 Dim: ", np.ndim(array3), "shape:", np.shape(array3))

print("---------------------------------------------------------------------")
print("---------------------------------------------------------------------")

newArray = np.concatenate((array1, array2, array3), axis=0)
print("\nnew array:\n", newArray)
print("\narry3 Dim: ", np.ndim(newArray), "shape:", np.shape(newArray))



arry1 Dim:  2 shape: (1, 2)

arry3 Dim:  2 shape: (2, 2)

arry3 Dim:  2 shape: (3, 2)
---------------------------------------------------------------------
---------------------------------------------------------------------

new array:
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]

arry3 Dim:  2 shape: (6, 2)


11. Sort 'newArray' in order into 'sortedArray'

In [46]:
sortedArray = np.sort(newArray)
print("\nsorted array:\n", sortedArray)
print("---------------------------------------------------------------------")
print("\nsorted array Dim: ", np.ndim(sortedArray), "shape:", np.shape(sortedArray))


sorted array:
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]
---------------------------------------------------------------------

sorted array Dim:  2 shape: (6, 2)


12. Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.

In [51]:
reshapedArray = sortedArray.reshape(3, 2, 2)

In [52]:
[[[a, b], [c, d]],
 [[e, f], [g, h]],
 [[i, j], [k, l]]] = reshapedArray

print("First group:", a, b, c, d)
print("Second group:", e, f, g, h)
print("Third group:", i, j, k, l)

First group: 16 25 2 11
Second group: 4 13 7 81
Third group: 5 6 11 12


13. Combined and sort the following arrays into one called 'comboArray' ...

    ```python
        one = ([10, 11, 12, 13, 14, 15, 16, 17])
        two = ([20, 21, 22, 23, 24, 25, 26, 27])
        three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
one = np.array(one)
two = np.array(two)
three = np.array(three)

comboArray = np.concatenate((one, two, three))
comboArray = np.sort(comboArray)
print("13. combo array:\n", comboArray)
print("Shape:", comboArray.shape)

13. combo array:
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
Shape: (24,)


14. Take 'comboArray' and perform the following slicing activities:
    - print sec1 - the 2nd element
    - print sec2 - all elements from the 3rd element to the last
    - print sec3 - all elements from the 4th to the 14th elements
    - print sec4 - the last 6 elements
    - print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
    - print sec6 - from #20 every even element to the end
    - print sec7 - from the last element moving forward, every 5th element

In [95]:
# - print sec1 - the 2nd element
sec1 = comboArray[1]
print(f"\nthe 2nd element = {sec1}\n")
# - print sec2 - all elements from the 3rd element to the last
sec2 = comboArray[2:]
print(f"all elements from the 3rd element to the last = {sec2}\n")
# - print sec3 - all elements from the 4th to the 14th elements
sec3 = comboArray[3:14]
print(f"all elements from the 4th to the 14th elements = {sec3}\n")
# - print sec4 - the last 6 elements
print("comboArray len:", len(comboArray))
sec4 = comboArray[-6:]
print(f"the last 6 elements = {sec4}\n")
# - print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
sec5 = comboArray[:-len(comboArray)+ 16]
print(f"all element from #0 up to #15 and including #15 = {sec5}\n")
# - print sec6 - from #20 every even element to the end
sec6 = comboArray[20::2]
print(f"from #20 every even element to the end = {sec6}\n")
 # - print sec7 - from the last element moving forward, every 5th element.
sec7 = comboArray[::-1][::5]

print(f"from the last element moving forward, every 5th element. = {sec7}\n")



the 2nd element = 1

all elements from the 3rd element to the last = [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]

all elements from the 4th to the 14th elements = [ 3  4  5  6  7 10 11 12 13 14 15]

comboArray len: 24
the last 6 elements = [22 23 24 25 26 27]

all element from #0 up to #15 and including #15 = [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17]

from #20 every even element to the end = [24 26]

from the last element moving forward, every 5th element. = [27 22 15 10  3]



15. Using `Series`, create a `DataFrame` that looks like this:

    | Ingredients | Quantity | Unit |
    |----|----|----|
    | Flour | 4 | cups |
    | Milk | 1 | cup |
    | Eggs | 2 | large |
    | Spam | 1 | can |

    Name: Dinner, dtype: object

In [93]:
import pandas as pd
ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name='Ingredients')
quantity = pd.Series([4, 1, 2, 1], name='Quantity')
unit = pd.Series(["cups", "cup", "large", "can"], name='Unit')
df = pd.concat([ingredients, quantity, unit], axis=1)
print(df)
df

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can

16. Take this data and create a DataFrame named studentData
    ```Python
        {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
    ```

In [97]:
studentData = pd.DataFrame (
    {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
)
studentData

Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

17. Add a new column to the DataFrame with the following deserts:
        ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

In [100]:

# NOTES: adding columns to dataframes (add list as column)
deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
# Using 'State' as the column name and equating it to the list
studentData['Deserts'] = deserts
print("\nDF with column from list ...\n", studentData)
studentData



DF with column from list ...
       Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa

18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

In [102]:
# Sorting the address DataFrame in Ascending order -- Sorting by columns: "Name", "address"
studentData.sort_values(by = ["Name", "address"], inplace = True)
studentData

Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        Deserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge

19. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:

    ```python
        df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
    ```

In [106]:
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df


Cows  Goats
Year 1    12     22
Year 2    20     19

In [ ]:
# write df to csv file
df.to_csv("cows_and_goats.csv")

20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

In [109]:
df2 = pd.DataFrame({'Carrots': [33, 65], 'Potatoes': [55, 66]}, index=['Winter', 'Spring'])
df2


Carrots  Potatoes
Winter       33        55
Spring       65        66

In [110]:
# write df to csv file
df2.to_csv("vegs.csv")

In [ ]:
# (B) cahnge and save a copy with different name
# Add a new column(single veg)
df2['Tomatoes'] = [40, 75]
df2.to_csv('vegs2.csv', index=True)  # Save copy with different name
print("\new DataFrame:")
df2


Modified DataFrame:


Carrots  Potatoes  Tomatoes
Winter       33        55        40
Spring       65        66        75